version: 2
updates:
  # Use `npm` as the ecosystem so Dependabot recognizes pnpm lockfiles (pnpm is
  # supported through the npm ecosystem when a pnpm-lock.yaml is present).
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "security"

  # Keep GitHub Actions up-to-date as a separate group
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  # Monorepo: also check the portfolio app manifests specifically to reduce
  # noise and target package updates for that package directory.
  - package-ecosystem: "npm"
    directory: "/apps/portfolio"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

