name: 'Setup monorepo (Node + pnpm)'
description: 'Lightweight composite action to setup Node.js and pnpm for repository workflows.'
author: 'automation'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version to prepare via corepack (or fallback to npm install)'
    required: false
    default: '10'

outputs:
  cache-hit:
    description: 'Indicates whether a cache was hit (best-effort; default false)'
    value: ${{ steps.emit.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Ensure pnpm is available
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - id: emit
      name: Emit outputs
      shell: bash
      run: |
        # This composite action cannot reliably detect cache hits across runners in a generic way.
        # Emit cache-hit=false by default to satisfy downstream workflows that reference it.
        echo "cache-hit=false" >> $GITHUB_OUTPUT
