name: 'Setup monorepo (Node + pnpm)'
description: 'Lightweight composite action to setup Node.js and pnpm for repository workflows.'
author: 'automation'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '22'
  pnpm-version:
    description: 'pnpm version to prepare via corepack (or fallback to npm install)'
    required: false
    default: '10'

outputs:
  cache-hit:
    description: 'Indicates whether a cache was hit (best-effort; default false)'
    value: ${{ steps.emit.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Ensure pnpm is available
      shell: bash
      run: |
        echo "🔧 Ensuring pnpm is available (requested version: ${{ inputs.pnpm-version }})"
        # Prefer corepack (modern Node) to avoid global installs
        if command -v pnpm >/dev/null 2>&1; then
          echo "pnpm already installed -> $(pnpm --version)"
        else
          if command -v corepack >/dev/null 2>&1; then
            corepack prepare pnpm@${{ inputs.pnpm-version }} --activate || true
          else
            echo "corepack not available, installing pnpm via npm"
            npm i -g pnpm@${{ inputs.pnpm-version }} || true
          fi
        fi
        echo "pnpm version: $(pnpm --version 2>/dev/null || echo 'unknown')"

    - id: emit
      name: Emit outputs
      shell: bash
      run: |
        # This composite action cannot reliably detect cache hits across runners in a generic way.
        # Emit cache-hit=false by default to satisfy downstream workflows that reference it.
        echo "cache-hit=false" >> $GITHUB_OUTPUT
