packages:
  - .

catalog:
  '@astrojs/cloudflare': 12.6.10
  '@astrojs/netlify': 6.5.12
  '@astrojs/node': 9.4.6
  '@astrojs/vercel': 8.2.9
  wrangler: 4.42.1

catalogMode: strict

cleanupUnusedCatalogs: true

engineStrict: true

linkWorkspacePackages: true

minimumReleaseAge: 1440

packageManagerStrictVersion: true

preferWorkspacePackages: true

resolutionMode: time-based

savePrefix: ''

strictDepBuilds: true

strictPeerDependencies: true
