packages:
  - apps/*
  - packages/*

catalog:
  wrangler: ^4.68.1

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@cloudflare/workers-types"
  - wrangler
  # Renovate security update: fast-xml-parser@5.3.8
  - fast-xml-parser@5.3.8
