name: Setup GitHub Token
description: Setup GitHub Token with fallback to GITHUB_TOKEN if PBOT_GITHUB_TOKEN is not available

runs:
  using: composite
  steps:
    - name: Setup Token with Fallback
      shell: bash
      run: |
        if [ -z "$PBOT_GITHUB_TOKEN" ]; then
          echo "ℹ️  PBOT_GITHUB_TOKEN not found, using GITHUB_TOKEN"
          echo "PBOT_GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
        else
          echo "✅ Using PBOT_GITHUB_TOKEN"
        fi
      env:
        PBOT_GITHUB_TOKEN: ${{ env.PBOT_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
