local_backend: true

logo_url: /favicon.svg

backend:
  name: github
  repo: yacosta738/yacosta738.github.io
  branch: main
  base_url: https://sveltia-cms-auth.yunielacosta738.workers.dev/

publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'


media_folder: "apps/portfolio/src/assets/images" # Location where files will be stored in the repo
public_folder: "apps/portfolio/src/assets/images" # The src attribute for uploaded media

i18n:
  structure: 'multiple_folders'
  locales: ['en', 'es']
  default_locale: 'en'

collections:
  # Skills Library Collection
  - name: "skillsLibrary"
    label: "Skills Library"
    label_singular: "Skill"
    description: "System skills library (icons, metadata, etc.)"
    folder: "apps/portfolio/src/data/skills"
    extension: "json"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string", required: false }

  # Languages Library Collection
  - name: "languagesLibrary"
    label: "Languages Library"
    label_singular: "Language"
    description: "Language names, mappings, and metadata"
    folder: "apps/portfolio/src/data/languages"
    extension: "json"
    create: true
    fields:
      - { label: "Code", name: "code", widget: "string" }
      - { label: "Native Name", name: "nativeName", widget: "string" }
      - label: "Names"
        name: "names"
        widget: "object"
        fields:
          - label: "English"
            name: "en"
            widget: "string"
            required: false
          - label: "Spanish"
            name: "es"
            widget: "string"
            required: false
          # Add more languages as needed
      - { label: "Flag", name: "flag", widget: "string", required: false }
      - { label: "Direction", name: "direction", widget: "select", options: ["ltr", "rtl"], default: "ltr" }

  - name: 'projectMetadata'
    i18n: true
    label: 'Project Metadata'
    folder: 'apps/portfolio/src/data/project-metadata'
    create: true
    extension: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Cover', name: 'cover', widget: 'image', i18n: 'duplicate' }
      - { label: 'Date', name: 'date', widget: 'datetime', i18n: 'duplicate' }
      - {
          label: 'Repository',
          name: 'repository',
          widget: 'string',
          required: false,
          i18n: 'duplicate',
        }
      - { label: 'URL', name: 'url', widget: 'string', required: false, i18n: 'duplicate' }
      - { label: 'Company', name: 'company', widget: 'string', required: false, i18n: true }
      - {
          label: 'Technologies',
          name: 'tech',
          widget: 'relation',
          collection: 'skillsLibrary',
          search_fields: ['name'],
          value_field: 'name',
          display_fields: ['name'],
          i18n: 'duplicate',
        }
      - {
          label: 'Show in projects',
          name: 'showInProjects',
          widget: 'boolean',
          default: false,
          i18n: 'duplicate',
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
          i18n: 'duplicate',
        }
      - { label: 'Priority', name: 'priority', widget: 'number', default: 0, i18n: 'duplicate' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: true,
          i18n: 'duplicate',
        }

  # Main Resume Collection (Multiple Languages)
  - name: "resume"
    label: "Resume"
    description: "Multi-language resume data"
    folder: "apps/portfolio/src/data/resume"
    extension: "json"
    create: true
    i18n: true
    fields:
      # Basics Section
      - label: "Basics"
        name: "basics"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Label", name: "label", widget: "string", i18n: true }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string", required: false}
          - { label: "URL", name: "url", widget: "string", required: false, i18n: true }
          - { label: "Summary", name: "summary", widget: "text", i18n: true }

          # Location
          - label: "Location"
            name: "location"
            widget: "object"
            fields:
              - { label: "Address", name: "address", widget: "string", required: false }
              - { label: "Postal Code", name: "postalCode", widget: "string", required: false }
              - { label: "City", name: "city", widget: "string" }
              - { label: "Country Code", name: "countryCode", widget: "string" }
              - { label: "Region", name: "region", widget: "string" }

          # Profiles
          - label: "Profiles"
            name: "profiles"
            widget: "list"
            fields:
              - { label: "Network", name: "network", widget: "string" }
              - { label: "Username", name: "username", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

      # Work Experience
      - label: "Work Experience"
        name: "work"
        widget: "list"
        fields:
          - { label: "Company Name", name: "name", widget: "string" }
          - { label: "Position", name: "position", widget: "string",i18n: true }
          - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Start Date"
            name: "startDate"
            widget: "datetime"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - label: "End Date"
            name: "endDate"
            widget: "datetime"
            required: false
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "Summary", name: "summary", widget: "text", required: false, i18n: true }
          - { label: "Highlights", name: "highlights", widget: "list", required: false, i18n: true }

      # Education
      - label: "Education"
        name: "education"
        widget: "list"
        fields:
          - { label: "Institution", name: "institution", widget: "string", i18n: true }
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Area of Study", name: "area", widget: "string", i18n: true }
          - { label: "Study Type", name: "studyType", widget: "string", i18n: true }
          - label: "Start Date"
            name: "startDate"
            widget: "date"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - label: "End Date"
            name: "endDate"
            widget: "date"
            required: false
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "Score", name: "score", widget: "string", required: false }
          - { label: "Courses", name: "courses", widget: "list", required: false, i18n: true }

      # Volunteer Experience
      - label: "Volunteer Experience"
        name: "volunteer"
        widget: "list"
        required: false
        fields:
          - { label: "Organization", name: "organization", widget: "string", i18n: true }
          - { label: "Position", name: "position", widget: "string", i18n: true }
          - { label: "URL", name: "url", widget: "string", required: false }
          - label: "Start Date"
            name: "startDate"
            widget: "date"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - label: "End Date"
            name: "endDate"
            widget: "date"
            required: false
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "Summary", name: "summary", widget: "text", required: false, i18n: true }
          - { label: "Highlights", name: "highlights", widget: "list", required: false, i18n: true }

      # Awards
      - label: "Awards"
        name: "awards"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - label: "Date"
            name: "date"
            widget: "date"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "Awarder", name: "awarder", widget: "string", i18n: true }
          - { label: "Summary", name: "summary", widget: "text", required: false, i18n: true }

      # Certificates
      - label: "Certificates"
        name: "certificates"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - label: "Date"
            name: "date"
            widget: "date"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "Issuer", name: "issuer", widget: "string", i18n: true }
          - { label: "URL", name: "url", widget: "string", required: false }

      # Publications
      - label: "Publications"
        name: "publications"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Publisher", name: "publisher", widget: "string", i18n: true }
          - label: "Release Date"
            name: "releaseDate"
            widget: "date"
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "URL", name: "url", widget: "string", required: false }
          - { label: "Summary", name: "summary", widget: "text", required: false, i18n: true }

      # Skills
      - label: "Skills"
        name: "skills"
        widget: "list"
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Level", name: "level", widget: "string", required: false, i18n: true }
          - { label: "Keywords", name: "keywords", widget: "list", required: false, i18n: true }

      # Languages
      - label: "Languages"
        name: "languages"
        widget: "list"
        required: false
        fields:
          - { label: "Language", name: "language", widget: "string", hint: "Use language code (e.g., 'en', 'es')", i18n: true }
          - { label: "Fluency", name: "fluency", widget: "string", i18n: true }

      # Interests
      - label: "Interests"
        name: "interests"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Keywords", name: "keywords", widget: "list", required: false, i18n: true }

      # References
      - label: "References"
        name: "references"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Reference", name: "reference", widget: "text", i18n: true }

      # Projects
      - label: "Projects"
        name: "projects"
        widget: "list"
        required: false
        fields:
          - { label: "Name", name: "name", widget: "string", i18n: true }
          - { label: "Description", name: "description", widget: "text", i18n: true }
          - { label: "Highlights", name: "highlights", widget: "list", required: false, i18n: true }
          - label: "Start Date"
            name: "startDate"
            widget: "date"
            required: false
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - label: "End Date"
            name: "endDate"
            widget: "date"
            required: false
            date_format: "YYYY-MM-DD"
            pattern:
              - "^\\d{4}-\\d{2}-\\d{2}$"
          - { label: "URL", name: "url", widget: "string", required: false }

  - name: 'articles'  
    label: 'Articles'
    label_singular: 'Article'
    folder: 'apps/portfolio/src/data/articles'
    create: true
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    extension: mdx
    i18n: true
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
        i18n: true
      - name: 'description'
        widget: 'string'
        label: 'Description'
        i18n: true
      - name: 'date'
        widget: 'datetime'
        label: 'Publish Date'
        i18n: 'duplicate'
      - name: 'lastModified'
        widget: 'datetime'
        label: 'Last Modified'
        required: false
        default: "{{now}}"
        i18n: 'duplicate'
      - name: 'author'
        widget: 'relation'
        collection: 'authors'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['name']
        display_fields: ['name']
        multiple: false
        i18n: 'duplicate'
      - name: 'cover'
        widget: 'image'
        label: 'Cover'
        i18n: 'duplicate'
        default: 'apps/portfolio/src/assets/images/blog-placeholder-1.avif'
      - name: 'tags'
        widget: 'relation'
        collection: 'tags'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: true
        i18n: 'duplicate'
      - name: 'category'
        widget: 'relation'
        collection: 'categories'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: false
        i18n: 'duplicate'
      - name: 'draft'
        widget: 'boolean'
        label: 'Draft'
        default: true
        i18n: 'duplicate'
      - name: 'featured'
        widget: 'boolean'
        label: 'Featured'
        default: false
        i18n: 'duplicate'
      - name: 'body'
        widget: 'markdown'
        label: 'Body'
        i18n: true

  - name: categories
    label: Categories
    label_singular: Category
    folder: apps/portfolio/src/data/categories
    slug: '{{title}}'
    create: true
    i18n: true
    fields:
      - name: title
        widget: string
        label: Title
        i18n: true
      - name: order
        widget: number
        label: Order
        required: false
        value_type: int
        min: -1000
        max: 1000
        step: 1
        default: 0
        i18n: 'duplicate'

  - name: tags
    label: Tags
    label_singular: Tag
    folder: apps/portfolio/src/data/tags
    slug: '{{title}}'
    create: true
    i18n: true
    fields:
      - name: title
        widget: string
        label: Title
        i18n: true

  - name: 'authors'
    label: 'Authors'
    label_singular: 'Author'
    folder: apps/portfolio/src/data/authors
    slug: '{{name}}'
    create: true
    extension: json
    i18n: true
    fields:
      - name: 'name'
        widget: 'string'
        label: 'Name'
        i18n: 'duplicate'
      - name: 'email'
        widget: 'string'
        label: 'Email'
        i18n: 'duplicate'
      - name: 'avatar'
        widget: 'image'
        label: 'Avatar'
        i18n: 'duplicate'
      - name: 'bio'
        widget: 'markdown'
        label: 'Bio'
        i18n: true
      - name: location
        widget: string
        label: Location
        i18n: true
      - name: socials
        widget: list
        label: Social Media
        i18n: 'duplicate'
        required: false
        summary: '{{fields.name}}'
        fields:
          - name: name
            widget: string
            label: Platform Name
            i18n: 'duplicate'
          - name: url
            widget: string
            label: Profile URL
            i18n: 'duplicate'
          - name: icon
            widget: string
            label: Icon (e.g., tabler:brand-github)
            i18n: 'duplicate'

  - name: 'externalArticles'  
    label: 'External Articles'
    label_singular: 'Article'
    folder: 'apps/portfolio/src/data/external-articles'
    create: true
    i18n: true
    path: '{{year}}/{{month}}/{{day}}/{{slug}}'
    extension: md
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
      - name: 'description'
        widget: 'string'
        label: 'Description'
      - name: 'date'
        widget: 'datetime'
        label: 'Publish Date'
      - name: 'lastModified'
        widget: 'datetime'
        label: 'Last Modified'
        required: false
        default: "{{now}}"
      - name: 'author'
        widget: 'relation'
        collection: 'authors'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['name']
        display_fields: ['name']
        multiple: false
      - name: 'cover'
        widget: 'image'
        label: 'Cover'
        default: 'apps/portfolio/src/assets/images/blog-placeholder-1.avif'
      - name: 'tags'
        widget: 'relation'
        collection: 'tags'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: true
      - name: 'category'
        widget: 'relation'
        collection: 'categories'
        value_field: '{{locale}}/{{slug}}'
        search_fields: ['title']
        display_fields: ['title']
        multiple: false
      - name: 'draft'
        widget: 'boolean'
        label: 'Draft'
        default: true
      - name: 'isExternal'
        widget: 'boolean'
        label: 'Is External'
        default: true
