local_backend: true

logo_url: /logo.svg

backend:
  name: 'github'
  repo: yacosta738/yacosta738.github.io
  branch: main
  base_url: https://yunielacosta.com
  automatic_deployments: false
  accept_roles:
    - admin
    - editor

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

publish_mode: editorial_workflow

media_folder: 'public/images'
public_folder: '/images'

i18n:
  structure: 'multiple_folders'
  locales: ['en', 'es']
  default_locale: 'en'
  canonical_slug:
    key: defaultLocaleVersion
    value: 'en/{{slug}}'

collections:
  - name: 'tech'
    label: 'Tech'
    folder: 'src/data/technologies'
    create: true
    extension: 'json'
    slug: '{{id}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'string' }
      - { label: 'url', name: 'url', widget: 'string' }

  - name: 'posts'
    i18n: true
    label: 'Blog Posts'
    folder: 'src/data/blog'
    create: true
    slug: '{{title | localize}}'
    fields:
      - name: 'title'
        widget: 'string'
        label: 'Title'
        i18n: true
      - name: 'description'
        widget: 'string'
        label: 'Description'
        i18n: true
      - name: 'link'
        widget: 'string'
        label: 'Link'
        required: false
        i18n: true
      - name: 'isExternalLink'
        widget: 'boolean'
        label: 'External Link'
        required: false
        i18n: 'duplicate'
      - name: 'date'
        widget: 'datetime'
        label: 'Date'
        i18n: 'duplicate'
      - name: 'cover'
        widget: 'image'
        label: 'Cover'
        required: false
        i18n: 'duplicate'
      - name: 'author'
        widget: 'relation'
        collection: 'authors'
        search_fields: ['name']
        value_field: '{{slug}}'
        display_fields: ['name']
        i18n: 'duplicate'
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          i18n: 'duplicate',
          required: false,
          collection: 'tags',
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
          multiple: true,
        }
      - {
          name: categories,
          label: Categories,
          widget: relation,
          i18n: duplicate,
          collection: categories,
          value_field: '{{slug}}',
          search_fields: ['title'],
          display_fields: ['title'],
          multiple: true,
        }
      - name: 'draft'
        widget: 'boolean'
        label: 'Draft'
        default: true
        i18n: 'duplicate'
      - name: 'body'
        widget: 'markdown'
        label: 'Body'
        i18n: true

  - name: 'jobs'
    i18n: true
    label: 'Jobs'
    folder: 'src/data/jobs'
    create: true
    extension: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Company', name: 'company', widget: 'string', i18n: true }
      - { label: 'URL', name: 'url', widget: 'string', required: false, i18n: 'duplicate' }
      - { label: 'Icon', name: 'icon', widget: 'string', i18n: 'duplicate' }
      - { label: 'Location', name: 'location', widget: 'string', i18n: true }
      - { label: 'Create Date', name: 'createDate', widget: 'datetime', i18n: 'duplicate' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: true,
          i18n: 'duplicate',
        }
      - {
          label: 'Roles',
          name: 'roles',
          widget: 'list',
          summary: '{{fields.role}} at {{fields.startDate}}',
          label_singular: 'Role',
          fields:
            [
              { label: 'Role', name: 'role', widget: 'string', i18n: true },
              { label: 'Start Date', name: 'startDate', widget: 'datetime', i18n: 'duplicate' },
              {
                label: 'End Date',
                name: 'endDate',
                widget: 'datetime',
                required: false,
                i18n: 'duplicate',
              },
              {
                label: 'Achievements',
                name: 'achievements',
                widget: 'list',
                allow_add: true,
                max: 4,
                i18n: true,
                field: { label: 'Achievement', name: 'achievement', widget: 'string' },
              },
            ],
        }

  - name: 'projects'
    i18n: true
    label: 'Projects'
    folder: 'src/data/projects'
    create: true
    extension: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Cover', name: 'cover', widget: 'image', i18n: 'duplicate' }
      - { label: 'Date', name: 'date', widget: 'datetime', i18n: 'duplicate' }
      - {
          label: 'Repository',
          name: 'repository',
          widget: 'string',
          required: false,
          i18n: 'duplicate',
        }
      - { label: 'URL', name: 'url', widget: 'string', required: false, i18n: 'duplicate' }
      - { label: 'Company', name: 'company', widget: 'string', required: false, i18n: true }
      - {
          label: 'Technologies',
          name: 'tech',
          widget: 'relation',
          collection: 'tech',
          search_fields: ['name'],
          value_field: 'name',
          display_fields: ['name'],
          i18n: 'duplicate',
        }
      - {
          label: 'Show in projects',
          name: 'showInProjects',
          widget: 'boolean',
          default: false,
          i18n: 'duplicate',
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
          i18n: 'duplicate',
        }
      - { label: 'Priority', name: 'priority', widget: 'number', default: 0, i18n: 'duplicate' }
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: true,
          i18n: 'duplicate',
        }
      - { label: 'Content', name: 'content', widget: 'markdown', i18n: true }

  - name: 'authors'
    i18n: true
    label: 'Authors'
    folder: 'src/data/authors'
    create: true
    slug: '{{name | localize}}'
    extension: 'json'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', i18n: 'duplicate' }
      - { label: 'Image', name: 'image', widget: 'image', i18n: 'duplicate' }
      - { label: 'Role', name: 'rol', widget: 'string', i18n: true }
      - { label: 'Bio', name: 'bio', widget: 'text', i18n: true }
      - { label: 'Email', name: 'email', widget: 'string', i18n: 'duplicate' }
      - {
          label: 'Social Media',
          name: 'social',
          widget: 'list',
          i18n: true,
          fields:
            [
              {
                label: 'Platform',
                name: 'platform',
                widget: 'select',
                options:
                  [
                    { label: 'GitHub', value: 'github' },
                    { label: 'LinkedIn', value: 'linkedin' },
                    { label: 'X (Twitter)', value: 'twitter' },
                  ],
                i18n: 'duplicate',
              },
              { label: 'Handle/ID', name: 'handle', widget: 'string', i18n: 'duplicate' },
            ],
        }

  - name: categories
    label: Categories
    label_singular: Category
    folder: src/data/categories
    slug: '{{title | localize}}'
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - {
          name: order,
          label: Order,
          widget: number,
          i18n: duplicate,
          required: false,
          value_type: int,
          min: -1000,
          max: 1000,
          step: 1,
        }

  - name: tags
    label: Tags
    label_singular: Tag
    folder: src/data/tags
    slug: '{{title | localize}}'
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: 'notifications'
    i18n: true
    label: 'Notifications'
    label_singular: 'Notification'
    folder: 'src/data/notifications'
    extension: 'md'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', required: true, i18n: true }
      - { name: 'content', label: 'Content', widget: 'markdown', required: true, i18n: true }
      - {
          name: 'type',
          label: 'Type',
          widget: 'select',
          options: ['neutral', 'success', 'error'],
          default: 'neutral',
          required: true,
          i18n: 'duplicate',
        }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime', i18n: duplicate }
      - { label: 'End Date', name: 'endDate', widget: 'datetime', i18n: duplicate, required: false }
      - {
          label: 'Dismissible',
          name: 'dismissible',
          widget: 'boolean',
          default: true,
          i18n: duplicate,
        }
      - { label: 'Active', name: 'active', widget: 'boolean', default: false, i18n: duplicate }
