#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit hook 🪝"

# Determine the package manager being used
if command -v pnpm >/dev/null 2>&1; then
	PACKAGE_MANAGER="pnpm"
elif command -v yarn >/dev/null 2>&1; then
	PACKAGE_MANAGER="yarn"
elif command -v npm >/dev/null 2>&1; then
	PACKAGE_MANAGER="npm"
else
	echo "No package manager found installed."
	exit 1
fi

echo "Using package manager: $PACKAGE_MANAGER"

# Install dependencies, generate translations, and format code
if $PACKAGE_MANAGER install && $PACKAGE_MANAGER run i18n:generate && $PACKAGE_MANAGER run format; then
	exit 0
else
	echo "Error: failed to run pre-commit hook"
	exit 1
fi
