name: Image Optimization

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.avif'

permissions:
  contents: write
  pull-requests: write

jobs:
  optimize:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Token
        uses: ./.github/actions/setup-token
        env:
          PBOT_GITHUB_TOKEN: ${{ secrets.PBOT_GITHUB_TOKEN }}

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ env.PBOT_GITHUB_TOKEN }}
          jpegQuality: '80'
          jpegProgressive: true
          pngQuality: '80'
          webpQuality: '80'
          ignorePaths: 'node_modules/**,dist/**,build/**,.astro/**,public/admin/**'
