name: Image Optimization

on:
  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
      - '**.avif'

# Explicit least-privilege permissions for image optimization
permissions:
  contents: write      # Required to commit optimized images
  pull-requests: write # Required to comment on PR with results

jobs:
  optimize:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Optimize Images
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Token
        uses: ./.github/actions/setup-token
        env:
          PBOT_GITHUB_TOKEN: ${{ secrets.PBOT_GITHUB_TOKEN }}

      - name: Compress Images
        uses: calibreapp/image-actions@05b1cf44e88c3b041b841452482df9497f046ef7
        with:
          githubToken: ${{ env.PBOT_GITHUB_TOKEN }}
          jpegQuality: '80'
          jpegProgressive: true
          pngQuality: '80'
          webpQuality: '80'
          ignorePaths: 'node_modules/**,dist/**,build/**,.astro/**,public/admin/**'
