#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/workspaces/yacosta738.github.io/node_modules/.pnpm/prebuild-install@7.1.1/node_modules/prebuild-install/node_modules:/workspaces/yacosta738.github.io/node_modules/.pnpm/prebuild-install@7.1.1/node_modules:/workspaces/yacosta738.github.io/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/workspaces/yacosta738.github.io/node_modules/.pnpm/prebuild-install@7.1.1/node_modules/prebuild-install/node_modules:/workspaces/yacosta738.github.io/node_modules/.pnpm/prebuild-install@7.1.1/node_modules:/workspaces/yacosta738.github.io/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../prebuild-install@7.1.1/node_modules/prebuild-install/bin.js" "$@"
else
  exec node  "$basedir/../../../../../prebuild-install@7.1.1/node_modules/prebuild-install/bin.js" "$@"
fi
